# Site settings
title: "Christopher Shen"
email: chrisshen@gatech.edu
description: >- # this means to ignore newlines until "baseurl:"
url:                https://csshen.github.io # main url
baseurl:            /
permalink:          /:title # Post permalink

logo_url: https://www.gettyimages.com/gi-resources/images/CreativeLandingPage/HP_Sept_24_2018/CR3_GettyImages-159018836.jpg
author_name: "Christopher Shen"

# Build settings
markdown: kramdown
#theme: the-plain
remote_theme: heiswayi/the-plain
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
